# SPDX-FileCopyrightText: 2026 Jandira Technologies, LLC
# SPDX-License-Identifier: AGPL-3.0-only
"""Build input.docx with python-docx's own default template.

Why python-docx and not `jubarte convert input.md`: this folder's
substituted-tool side is python-docx's documented table/list idiom
(`add_table(..., style="Table Grid")`, `style="List Bullet"`), and those
style *names* only exist in a template that defines them — python-docx's
default template does, a jubarte-built docx does not (see
pydocx_style_gap.txt, generated by run.sh). Building the input from the
python-docx template gives both sides the same starting file and gives
python-docx its best case; jubarte edits any valid .docx either way.

The letter text mirrors input.md.
"""

from datetime import datetime, timezone

from docx import Document

doc = Document()

props = doc.core_properties
props.created = datetime(2026, 1, 12, 9, 0, tzinfo=timezone.utc)
props.modified = datetime(2026, 1, 12, 9, 0, tzinfo=timezone.utc)
props.last_modified_by = "People Operations"
props.author = "People Operations"

doc.add_heading("Onboarding Letter", level=1)
doc.add_paragraph(
    "Welcome to Northwind Traders. This letter confirms your start "
    "date of 2 February 2026."
)
doc.add_paragraph(
    "Your manager will schedule introductions during week one. "
    "Equipment ships to your home address before day one."
)
doc.add_paragraph("The checklist below is maintained by People Operations.")
doc.add_paragraph("Signed offer letter on file")
doc.add_paragraph("Payroll direct deposit form")
doc.add_paragraph("Badge photo uploaded")
doc.add_paragraph("Complete the safety module")
doc.add_paragraph("Book the week-one introductions")
doc.add_paragraph(
    "Payroll runs on the last day of each month. Direct deposit forms "
    "are due before your start date."
)
doc.add_paragraph("Questions go to people-ops@northwind.example.")

doc.save("input.docx")
print("wrote input.docx")
