#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Jandira Technologies, LLC
# SPDX-License-Identifier: AGPL-3.0-only
# Regenerate help-cli.md: every `--help` screen of the jubarte CLI, verbatim.
set -euo pipefail
cd "$(dirname "$0")"
JUBARTE="${JUBARTE:-jubarte}"
OUT=help-cli.md

screen() {
  printf '\n## `jubarte %s--help`\n\n```text\n' "${*:+$* }"
  "$JUBARTE" "$@" --help
  printf '```\n'
}

{
  # REUSE-IgnoreStart
  printf '<!-- SPDX-FileCopyrightText: 2026 Jandira Technologies, LLC -->\n'
  printf '<!-- SPDX-License-Identifier: AGPL-3.0-only -->\n\n'
  # REUSE-IgnoreEnd
  printf '# jubarte CLI help\n\n'
  printf 'Every `--help` screen of `%s`, generated by `gen-help.sh`.\n' "$("$JUBARTE" --version)"
  printf 'Do not edit by hand: rerun `JUBARTE=path/to/jubarte bash examples/cli/gen-help.sh`.\n'
  printf '`-h` prints the short form of each screen; the long form is below.\n\n'
  printf '## Contents\n\n'
  printf -- '- [`jubarte --help`](#jubarte---help)\n'
  # Tasks in the order the top-level help lists them.
  tasks=$("$JUBARTE" --help | awk '/^Tasks:/{t=1;next} t&&/^$/{exit} t&&/^  [a-z]/{print $1}' | grep -v '^help$')
  for t in $tasks; do
    printf -- '- [`jubarte %s --help`](#jubarte-%s---help)\n' "$t" "$t"
    for s in $("$JUBARTE" "$t" --help | awk '/^Commands:/{c=1;next} c&&/^$/{exit} c&&/^  [a-z]/{print $1}' | grep -v '^help$'); do
      printf -- '  - [`jubarte %s %s --help`](#jubarte-%s-%s---help)\n' "$t" "$s" "$t" "$s"
    done
  done
  screen
  for t in $tasks; do
    screen "$t"
    for s in $("$JUBARTE" "$t" --help | awk '/^Commands:/{c=1;next} c&&/^$/{exit} c&&/^  [a-z]/{print $1}' | grep -v '^help$'); do
      screen "$t" "$s"
    done
  done
} > "$OUT"
echo "wrote $OUT"
