#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Jandira Technologies, LLC
# SPDX-License-Identifier: AGPL-3.0-only
# Regenerate every output in out/ and the guide VISUALIZE.md: the ways an
# agent driving the jubarte CLI can look at (1) a document, (2) the result of
# editing a document that already carries tracked changes and comments, and
# (3) the differences between two documents, with each view's options (4).
set -euo pipefail
cd "$(dirname "$0")"
JUBARTE="${JUBARTE:-jubarte}"
GUIDE=VISUALIZE.md
DPI=60 # small pages keep the committed PNGs light; agents use 96+ to read
MAX_LINES=40

rm -rf out edited plan.json
mkdir -p out

# show TITLE CMD...: run CMD (the `jubarte` word in it is $JUBARTE), and append
# the command and its stdout+stderr to the guide, cut at MAX_LINES lines.
# A non-zero exit is recorded, never fatal: exit 2 and 5 are answers here.
show() {
  local title=$1
  shift
  local status=0 out
  out=$("$JUBARTE" "$@" 2>&1) || status=$?
  {
    printf '\n%s\n\n```console\n$ jubarte' "$title"
    printf ' %q' "$@"
    printf '\n'
    printf '%s\n' "$out" | head -n "$MAX_LINES"
    local lines
    lines=$(printf '%s\n' "$out" | wc -l | tr -d ' ')
    if [ "$lines" -gt "$MAX_LINES" ]; then
      printf '… (%s more lines)\n' "$((lines - MAX_LINES))"
    fi
    if [ "$status" -ne 0 ]; then
      printf '[exit %s]\n' "$status"
    fi
    printf '```\n'
  } >> "$GUIDE"
}

# image CAPTION FILE: embed a PNG the previous command wrote.
image() {
  printf '\n![%s](%s)\n' "$1" "$2" >> "$GUIDE"
}

say() {
  printf '\n%s\n' "$*" >> "$GUIDE"
}

cat > "$GUIDE" <<'EOF'
<!-- SPDX-FileCopyrightText: 2026 Jandira Technologies, LLC -->
<!-- SPDX-License-Identifier: AGPL-3.0-only -->

# How an agent sees documents with the jubarte CLI

Generated by `run.sh` from [`received.md`](received.md) and
[`plan.template.json`](plan.template.json); every block below is the real
output of the command above it. Do not edit by hand: rerun
`JUBARTE=path/to/jubarte bash examples/cli/visualize/run.sh`.
Every option of every command is listed in [`../help-cli.md`](../help-cli.md).

An agent has three kinds of eyes:

- **Text views** (`text`, `convert -t md`, `diff`, `changes`, `comments`,
  `inspect`): cheap, exact, greppable, and carry the IDs edit plans need.
- **Page views** (`convert --png`/`--pdf`, `edit --png`, `diff -o x.png`):
  what a person sees in Word, for layout, balloons and revision colours.
- **Machine views** (`--json` everywhere, `--report`, `diff-render --json`):
  for checking a result instead of reading it.

The document is a consulting agreement that Ann Counsel already redlined:
nine tracked changes (insertions, deletions, a table cell change) and two
comments, built from CriticMarkup:

```bash
jubarte convert received.md -o out/received.docx --author "Ann Counsel" --date 2026-10-01T09:00:00Z
```

Pages are rendered at 60 dpi to keep this folder small; read them at 96 dpi
or more.
EOF

"$JUBARTE" convert received.md -o out/received.docx --author "Ann Counsel" \
  --date 2026-10-01T09:00:00Z --force > /dev/null
R=out/received.docx

# ---------------------------------------------------------------------------
say '## 1. Visualize a document'
say '### 1.1 Read it as text'
show 'The edit view: Markdown with the `[body:p:N]` IDs an edit plan names. Revisions show as their current text.' \
  text "$R"
show '`--track-changes all`: the tracked changes and comments as CriticMarkup, with author and date.' \
  text "$R" --track-changes all
show '`--track-changes accept`: the text as it reads once every change is accepted.' \
  text "$R" --track-changes accept
show '`--track-changes reject`: the text as it read before the changes.' \
  text "$R" --track-changes reject

say '### 1.2 Read it as Markdown with pages'
show '`convert -t md`: CriticMarkup plus `<!-- page N of M -->` lines from the layout, so an agent knows which page text lands on.' \
  convert "$R" -t md
show '`--no-page-markers` skips the layout pass; `--track-changes accept|reject` resolves the changes in the Markdown itself.' \
  convert "$R" -t md --no-page-markers --track-changes accept

say '### 1.3 List what changed and who said what'
show '`changes`: one line per tracked change, with the `body:rev:N` IDs that `accept`, `reject` and edit plans select.' \
  changes "$R"
show '`changes --json`: the same as JSON lines.' \
  changes "$R" --json
show '`revisions`: the revision summary of a redline.' \
  revisions "$R"
show '`comments`: comments, their anchors, replies and resolved state. `--json`, `--author NAME` and `--latest` (newest per thread) narrow it.' \
  comments "$R"
show '' comments "$R" --json --author "Ann Counsel"

say '### 1.4 Inspect the structure'
show '`inspect`: document facts, paragraph styles and tables.' \
  inspect "$R"
show '`inspect --tables`: each table as a grid, with cell IDs.' \
  inspect "$R" --tables
"$JUBARTE" inspect "$R" --json > out/inspect.json
say '`inspect --json` writes the full snapshot (`schema_version`, `source_sha256`, `summary`, `paragraphs`, `stories`, `tables`): [`out/inspect.json`](out/inspect.json). Its `source_sha256` is the value an edit plan pins.'
show '`debug --check render`: what each story should put on the page (tables, fonts and what replaces them, revisions, sections).' \
  debug "$R" --check render

say '### 1.5 See the pages'
show '`convert --png`: every page as PNG, with `--report` (page count, each page'"'"'s text, fonts) and `--font-report` (how each requested font resolved).' \
  convert "$R" --png --dpi "$DPI" -o out/received.pdf --report out/received-report.json \
  --font-report out/received-fonts.json --force
image 'received.docx, conventional marks' out/received-page-01.png
say 'Conventional marks (the default): deletions red and struck, insertions blue and underlined, moves green; comments in balloons on the right.'

show '`--revisions word`: the markup Microsoft Word paints when it saves as PDF. Use it whenever the page is compared with one of Word'"'"'s.' \
  convert "$R" --png --dpi "$DPI" -o out/received-word.pdf --revisions word --force
image 'received.docx, Word marks' out/received-word-page-01.png

show '`--revisions custom --revision-palette`: pick each kind'"'"'s colour and line (`strike`, `double-strike`, `underline`, `double-underline`, `plain`).' \
  convert "$R" --png --dpi "$DPI" -o out/received-custom.pdf --revisions custom \
  --revision-palette 'deleted=#8E44AD:double-strike,inserted=#117A65:double-underline' --force
image 'received.docx, custom palette' out/received-custom-page-01.png

show '`--move-comments`: comments listed after the last page; the commented text keeps its tint and a `[JR1]` marker, and the page keeps its own width.' \
  convert "$R" --png --dpi "$DPI" -o out/received-endnotes.pdf --move-comments --force
image 'received.docx, comments after the text, page 1' out/received-endnotes-page-01.png
image 'received.docx, the comment listing' out/received-endnotes-page-02.png

show '`--pdf` (the default) writes the PDF; `--compress` deflates its streams. `--pages 1` rasterizes only page 1 (layout still covers the whole document); `--changed-only` keeps only pages a tracked change touches.' \
  convert "$R" --pdf --compress -o out/received-compressed.pdf --force
show '' convert "$R" --png --pages 1 --changed-only --dpi "$DPI" -o out/received-changed.pdf --force

say '### 1.6 Check it before trusting it'
show '`validate`: will Word open it without a repair prompt? (findings: exit 2)' validate "$R"
show '`audit`: accessibility, style and structure findings (findings: exit 2).' audit "$R"

# ---------------------------------------------------------------------------
say '## 2. Edit a document that already has tracked changes and comments'
say 'The agent answers Ann'"'"'s comments and makes two edits of its own with an edit plan. `"existing_revisions": "keep"` keeps her nine changes as they are; the plan pins the `source_sha256` of `received.docx`, so it cannot be applied to another version of the file. The plan in this folder is [`plan.template.json`](plan.template.json) with that hash filled in.'
sed "s/@SHA@/$(shasum -a 256 "$R" | cut -d' ' -f1)/" plan.template.json > out/plan.json

show '`edit --dry-run`: resolve every operation and report, write nothing. A plan that cannot apply exits 3 with the reason.' \
  edit "$R" --plan out/plan.json --out-dir out/edited --dry-run
show '`edit --pdf --png`: write `clean.docx` (every change accepted), `redline.docx` (Ann'"'"'s changes plus the agent'"'"'s), `patch.diff`, `report.jsonl`, and both as PDF and PNG.' \
  edit "$R" --plan out/plan.json --out-dir out/edited --pdf --png --dpi "$DPI"
image 'redline.docx: both authors'"'"' changes, the reply and the resolved comment' out/edited/redline-page-01.png
image 'clean.docx: every change accepted' out/edited/clean-page-01.png

say '### 2.1 What the edit did, as text'
say '`patch.diff`: only the paragraphs the plan touched, as `git diff --word-diff` with CriticMarkup comments:'
{
  printf '\n```diff\n'
  cat out/edited/patch.diff
  printf '```\n'
} >> "$GUIDE"
say '`report.jsonl`: one line per operation, then a summary (`status`, operations ok/failed, revisions and comments added):'
{
  printf '\n```json\n'
  cat out/edited/report.jsonl
  printf '```\n'
} >> "$GUIDE"
show '`changes` on the redline: the agent'"'"'s revisions sit beside Ann'"'"'s, each with its author.' \
  changes out/edited/redline.docx
show '`comments` on the redline: the reply names its parent and the resolved comment says so.' \
  comments out/edited/redline.docx
show '`comments --latest`: one comment per thread, the newest.' \
  comments out/edited/redline.docx --latest
show '`text --track-changes all` on the redline: the whole document with every change and comment.' \
  text out/edited/redline.docx --track-changes all

say '### 2.2 What the edit did, as pages'
show '`diff-render`: which rendered pages moved, and where (different pages: exit 5). With `--out-dir`, each changed page is written as before, after and a magenta overlay.' \
  diff-render "$R" out/edited/redline.docx --out-dir out/diff-render --dpi "$DPI" --force
image 'diff-render overlay: changed pixels in magenta, boxed' out/diff-render/diff-page-01.png
show '`diff-render --json`: the same answer for a script (`changed_ratio`, `bbox`, `only_in`).' \
  diff-render "$R" out/edited/redline.docx --json --dpi "$DPI"
show '`edit --revisions word`: the same plan, its redline painted as Word paints it.' \
  edit "$R" --plan out/plan.json --out-dir out/edited-word --png --dpi "$DPI" --revisions word
image 'redline.docx, Word marks' out/edited-word/redline-page-01.png

# ---------------------------------------------------------------------------
say '## 3. Diff two documents'
say 'Old is `received.docx`, new is the agent'"'"'s `redline.docx`. Each view keeps both documents'"'"' tracked marks unless it says otherwise. `-a` and `-d` pin the author and date so this guide is reproducible; by default they are `git config user.name` and now.'
O="$R"
N=out/edited/redline.docx
PIN=(-a Agent -d 2026-10-02T15:00:00Z)

say '### 3.1 Text views'
show '`--format patch` (the default): the changed paragraphs as `git diff --word-diff` with CriticMarkup comments and highlights. `--columns N` wraps it (0: no wrap).' \
  diff "$O" "$N" "${PIN[@]}"
say 'With a Word document on either side, `patch` and `critic` also write a Word redline (`<old>_v_<new>.docx` beside the old document unless `-o` names another path), so the next run needs `--force`.'
show '`--format critic`: the whole new document as CriticMarkup.' \
  diff "$O" "$N" --format critic --force "${PIN[@]}"
show '`--format github`: a Git/GitHub unified diff of the two documents'"'"' text, tracked marks preserved; `-U N` sets the context lines.' \
  diff "$O" "$N" --format github
show '`-U0`: changed lines only.' \
  diff "$O" "$N" --format github -U0
show '`--accept-changes`: accept both documents'"'"' changes first, so only the outcome differs.' \
  diff "$O" "$N" --format github --accept-changes
show '`--format word`: fresh word-level CriticMarkup after accepting ALL changes in both documents.' \
  diff "$O" "$N" --format word
show '`--format normal`: line addresses (`a`/`d`/`c`), `<` and `>` lines, no context.' \
  diff "$O" "$N" --format normal
show '`--format context`: old/new range blocks with `!`, `+` and `-` prefixes.' \
  diff "$O" "$N" --format context
show '`--format side-by-side`: old and new in columns with `|`, `<` and `>` markers. Lines are cut to a 70-character window around the change; `--full-lines` shows them whole.' \
  diff "$O" "$N" --format side-by-side
show '' diff "$O" "$N" --format side-by-side --full-lines -U0

say '### 3.2 Word, PDF and page views'
show '`diff -o x.docx` (or `compare`): a Word redline of old against new, every difference a tracked change by `--author`.' \
  diff "$O" "$N" -o out/diff.docx --force "${PIN[@]}"
show '' compare "$O" "$N" -o out/compare.docx --force -a Agent -d 2026-10-02T15:00:00Z
show '`compare --mode powertools`: Open-Xml-PowerTools'"'"' coarser paragraph-level redline instead of Word'"'"'s.' \
  compare "$O" "$N" -o out/compare-powertools.docx --mode powertools --force -a Agent -d 2026-10-02T15:00:00Z
show '`changes` on the comparison: what Compare marked.' changes out/compare.docx
show '`diff -o x.png`: the redline'"'"'s pages, with every `convert` page option: `--revisions`, `--revision-palette`, `--move-comments`, `--changed-only`.' \
  diff "$O" "$N" -o out/diff.png --force --revisions word --move-comments "${PIN[@]}"
image 'diff -o diff.png --revisions word --move-comments, page 1' out/diff-page-01.png
show '`diff -o x.pdf --changed-only`: only the pages a change touches.' \
  diff "$O" "$N" -o out/diff-changed.pdf --force --changed-only "${PIN[@]}"
show '`debug A B --check text`: the two packages'"'"' paragraphs, only the lines that differ, with `{+inserted+}` and `[-deleted-]` runs.' \
  debug "$O" "$N" --check text

say '### 3.3 Markdown on either side'
say 'The same views work on Markdown. Here the agent'"'"'s version of the Markdown source is compared with Ann'"'"'s; `--critic` reads the CriticMarkup as tracked changes instead of text.'
sed -e 's/March 1, 2026/April 1, 2026/' \
  -e 's/secret{>>Add a three-year survival period?<<}/secret for three years after this Agreement ends/' \
  received.md > out/agent.md
show '' diff received.md out/agent.md --format github -U1
show '' diff received.md out/agent.md --format word
show '`diff X.docx Y.md -o x.docx`: the Markdown'"'"'s edits as tracked changes on the Word document.' \
  diff "$R" out/agent.md -o out/from-markdown.docx --force "${PIN[@]}"

# ---------------------------------------------------------------------------
cat >> "$GUIDE" <<'EOF'

## 4. Every visualization and its options

| View | Command | Options that change what is shown |
|---|---|---|
| Edit view with IDs | `text FILE` | `--track-changes all\|accept\|reject` (CriticMarkup, no IDs) |
| Markdown with pages | `convert FILE -t md` | `--no-page-markers`, `--track-changes all\|accept\|reject`, `-o FILE` |
| Tracked changes | `changes FILE` | `--json` |
| Comments | `comments FILE` | `--json`, `--author NAME`, `--latest` |
| Structure | `inspect FILE` | `--json`, `--tables` |
| Render triage | `debug FILE --check render` | `--check text\|runs\|xml\|changes\|…`, two files print only differences |
| Pages | `convert FILE --png` / `--pdf` | `--dpi`, `--pages`, `--revisions conventional\|word\|custom`, `--revision-palette`, `--move-comments`, `--changed-only`, `--compress`, `--report`, `--font-report`, `--fail-on-substitution`, `--timeout` |
| Validity | `validate FILE`, `audit FILE` | `validate --repair`, `--json` (see `--help`) |
| Edit result | `edit FILE --plan P --out-dir D` | `--dry-run`, `--pdf`, `--png`, `--dpi`, `--revisions`, `--revision-palette`, `--quiet`; writes `patch.diff`, `report.jsonl`, `clean.*`, `redline.*` |
| Text diff | `diff OLD NEW` | `--format patch\|critic\|github\|word\|normal\|context\|side-by-side`, `-U N`, `--accept-changes`, `--full-lines`, `--columns N`, `-f md\|docx`, `--critic` |
| Word redline | `compare OLD NEW`, `diff OLD NEW -o x.docx` | `--mode word\|powertools`, `--detail-threshold`, `-a`, `-d`, `--reference-doc` |
| Redline pages | `diff OLD NEW -o x.pdf\|x.png` | every page option of `convert` |
| Pixel diff | `diff-render A B` | `--out-dir`, `--json`, `--no-overlay`, `--dpi` |
| Package diff | `debug A B`, `debug diff A B` | `--check …`, `--raw` |

Which to reach for:

- To decide what to edit: `text` (IDs) and `changes`/`comments` (revision
  and comment IDs).
- To check an edit: `edit`'s `report.jsonl` (status), `patch.diff` (just the
  touched paragraphs), then `diff-render` (did the layout move, exit 5).
- To show a person: `convert --png` or `diff -o x.pdf`; add
  `--revisions word` whenever the page is compared with Word's.
- To review two versions: `diff --format github` for text, `--accept-changes`
  or `--format word` when only the final wording matters.
EOF
echo "wrote $GUIDE and out/"
